### PR TITLE
Cart UI updates

### LINKED ISSUE #37: Improve user experience and education on vote credits.
Figma: https://www.figma.com/design/4XYqJxQDUYGv1WADgFoLvR/MACI-QF?t=fNt7zQS2F8GixKCk-0

### PR DESCRIPTION
**Pull request by codenamejason**
fixes #37

### CODE REVIEW

**Review by melissa-neira — CHANGES_REQUESTED** [review]
inputting my eth donation is a bit wonky, the default is 0 and when I try to input a whole number, it gets defaulted to a decimal point. can we make this interaction a bit smoother?

let's also show commas to indicate large numbers (ex. 10,000 or 100,000)

**Comment by 0xKurt** [comment]
Great Job!

One small thing i noticed:
If I hit the limit of the credits and i increase the eth value, the error is still present, but it should be updated accordingly

@melissa-neira also I would like to see a message somewhere, that left over credits are not spent. (The remaining ETH are not spent if not all credits are used, or sth like that)

**Comment by nijoe1** [comment]
One more thing to consider is storing the total contribution amount in local storage per round. Currently, the total contribution is recalculated after refreshing the page based on the voice credits given to each project. This means that if someone has not spent their voice credits and reloads the page, the total contributions will decrease. This issue has been observed previously.

**Comment by bhargavaparoksham** [comment]
@melissa-neira this is because currently it doesn't allow you to input anything higher than your eligible amount. I'll fix this in another pr.

**Review by 0xKurt — APPROVED** [review]

**Pull request merged**
